apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckscheduler
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bckscheduler
    spec:
      containers:
      - name: bckscheduler
        image: acrsatrack.azurecr.io/backend_scheduler:1.0.0        
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m		
      imagePullSecrets:
      - name: denkerskey
