apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bcktmrerrorreader
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bcktmrerrorreader
    spec:
      containers:
      - name: bcktmrerrorreader
        image: acrsatrack.azurecr.io/error_reader:1.0.1        
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m		
      imagePullSecrets:
      - name: registrosatrack
