apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckactivationservices
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bckactivationservices
    spec:
      containers:
      - name: bckactivationservices
        image: acrsatrack.azurecr.io/backend_activation_services:1.0.4
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: test
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m		
      imagePullSecrets:
      - name: denkerskey
      
---
apiVersion: v1
kind: Service
metadata:
  name: bckactivationservices
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bckactivationservices
