apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{ImageName}#
spec:
  replicas: 2
  selector:
    matchLabels:
      app: #{ImageName}#
  template:
    metadata:
      labels:
        app: #{ImageName}#
    spec:
      containers:
      - name: #{ImageName}#
        image: #{AcrProd}#/#{ImageName}#:#{VersionImage}#
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: #{Environment}#
        resources:
          requests:
            cpu: 50m
            memory: 350Mi
          limits:
            cpu: 300m
            memory: 350Mi  
      imagePullSecrets:
      - name: registrosatrack  
