apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: invoicing-invoice-filegeneration
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: invoicing-invoice-filegeneration
    spec:
      containers:
      - name: invoicing-invoice-filegeneration
        image: acrdenkers.azurecr.io/invoicing_invoice_filegeneration:3159
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registrosatrack
---
apiVersion: v1
kind: Service
metadata:
  name: invoicing-invoice-filegeneration
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: invoicing-invoice-filegeneration
