apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: invoicing_invoice_filegeneration
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: invoicing_invoice_filegeneration
    spec:
      containers:
      - name: invoicing_invoice_filegeneration
        image: acrdenkers.azurecr.io/invoicing_invoice_filegeneration:3158
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registrosatrack
---
apiVersion: v1
kind: Service
metadata:
  name: invoicing_invoice_filegeneration
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: invoicing_invoice_filegeneration
