apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: invoicing-invoice-filegeneration
  namespace: invoicing
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: invoicing-invoice-filegeneration
    spec:
      containers:
      - name: invoicing-invoice-filegeneration
        image: TestRegistroContenedores/invoicing_invoice_filegeneration:7715
        ports:
        - containerPort: 80
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Development"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:80"
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
            memory: 450Mi
      imagePullSecrets:
      - name: registrosatrack
---
apiVersion: v1
kind: Service
metadata:
  name: invoicing-invoice-filegeneration
  namespace: invoicing
  labels:
    run: invoicing-invoice-filegeneration
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: invoicing-invoice-filegeneration
