apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bckapilistenerkc
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bckapilistenerkc
    spec:
      containers:
      - name: bckapilistenerkc
        image: acrsatrack.azurecr.io/backend_listener:1.2.0
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m		
      imagePullSecrets:
      - name: registrosatrack
      
---
apiVersion: v1
kind: Service
metadata:
  name: bckapilistenerkc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bckapilistenerkc
