apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bcklapilistener
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: bcklapilistener
    spec:
      containers:
      - name: bcklapilistener
        image: acrsatrack.azurecr.io/listener:1.0.1
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m		
      imagePullSecrets:
      - name: denkerskey
      
---
apiVersion: v1
kind: Service
metadata:
  name: bcklapilistener
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: bcklapilistener
