apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bcktmrsecurity
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bcktmrsecurity
    spec:
      containers:
      - name: bcktmrsecurity
        image: acrsatrack.azurecr.io/security:1.0.3    
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m		
      imagePullSecrets:
      - name: registrosatrack
